server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:nodejs_demo}
#    username: ${MYSQL_USERNAME}
#    password: ${MySQL_PASSWORD}
    url: jdbc:mysql://sh-cynosdbmysql-grp-9njbsvv6.sql.tencentcdb.com:25244/nodejs_demo?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: BanJiu123456
  mvc:
    view:
      suffix: .html
      prefix: /



mybatis-plus:
  configuration:

    auto-mapping-behavior: full
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete
      id-type: assign_id